package dao; import java.sql.*; import model.Vehicle; import util.db;
public class VehicleDAO {
    private void print(ResultSet rs)throws Exception{System.out.println(rs.getInt("id")+" | "+rs.getString("vehicle_number")+" | "+rs.getString("owner_name")+" | "+rs.getString("vehicle_type")+" | In:"+rs.getString("entry_time")+" | Out:"+rs.getString("exit_time")+" | Rs."+rs.getDouble("charges")+" | "+rs.getString("status"));}
    public boolean add(Vehicle v){try{PreparedStatement ps=db.getConnection().prepareStatement("INSERT INTO vehicles(vehicle_number,owner_name,vehicle_type,entry_time,exit_time,charges,status)VALUES(?,?,?,?,?,?,?)");ps.setString(1,v.getVehicleNumber());ps.setString(2,v.getOwnerName());ps.setString(3,v.getVehicleType());ps.setString(4,v.getEntryTime());ps.setString(5,v.getExitTime());ps.setDouble(6,v.getCharges());ps.setString(7,v.getStatus());return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void viewAll(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM vehicles").executeQuery();boolean f=false;while(rs.next()){f=true;print(rs);}if(!f)System.out.println("No vehicles.");}catch(Exception e){}}
    public void searchById(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("SELECT * FROM vehicles WHERE id=?");ps.setInt(1,id);ResultSet rs=ps.executeQuery();if(rs.next())print(rs);else System.out.println("Not found.");}catch(Exception e){}}
    public void activeVehicles(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM vehicles WHERE status='Parked'").executeQuery();boolean f=false;System.out.println("Currently Parked:");while(rs.next()){f=true;print(rs);}if(!f)System.out.println("Parking is empty.");}catch(Exception e){}}
    public boolean exitVehicle(int id,double charges){try{PreparedStatement ps=db.getConnection().prepareStatement("UPDATE vehicles SET status='Exited',charges=? WHERE id=?");ps.setDouble(1,charges);ps.setInt(2,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public boolean delete(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("DELETE FROM vehicles WHERE id=?");ps.setInt(1,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void totalRevenue(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT SUM(charges) FROM vehicles WHERE status='Exited'").executeQuery();if(rs.next())System.out.println("Total Revenue: Rs."+rs.getDouble(1));}catch(Exception e){}}
    public void vehicleTypeReport(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT vehicle_type,COUNT(*) as cnt FROM vehicles GROUP BY vehicle_type").executeQuery();System.out.println("Type | Count");while(rs.next())System.out.println(rs.getString("vehicle_type")+" | "+rs.getInt("cnt"));}catch(Exception e){}}
}
